const c=document.querySelector('#world'),x=c.getContext('2d'),ui=id=>document.getElementById(id);let W,H,dpr;
const state={t:0,epoch:0,carrier:0,chaos:1,eventT:0,eventEvery:14,secret:[],fuzzball:false,frontier:null};
const player={x:0,y:0,vx:0,vy:0,hp:100,xp:0,level:1};const keys=new Set();const mobs=[],signals=[];
const profile=JSON.parse(localStorage.getItem('df-mmorpg')||'null')||{moves:0,pulses:0,events:0,failures:0,discoveries:[]};
function save(){localStorage.setItem('df-mmorpg',JSON.stringify(profile))}function resize(){dpr=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;c.width=W*dpr;c.height=H*dpr;x.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);resize();
const frontierProblems=[
 {name:'Quantum Gravity',q:'What framework consistently unifies quantum theory with dynamical spacetime?',boundary:'No experimentally confirmed complete quantum-gravity theory.',probe:'Look for observables that distinguish candidate low-energy or cosmological signatures.'},
 {name:'Black Hole Information',q:'How is quantum information preserved through black-hole formation and evaporation?',boundary:'Semiclassical reasoning, unitarity and spacetime descriptions remain in tension in important regimes.',probe:'Track which assumptions must change when information recovery is enforced.'},
 {name:'Measurement Problem',q:'What physical account, if any, selects definite outcomes from quantum superpositions?',boundary:'Interpretations reproduce ordinary quantum predictions but differ in ontology and sometimes proposed extensions.',probe:'Separate interpretation from experimentally distinguishable modification.'},
 {name:'Dark Matter',q:'What accounts for the gravitational evidence attributed to dark matter?',boundary:'Many candidates remain viable; none is established as the complete explanation.',probe:'Seek discriminating signatures across astrophysical, direct and collider searches.'},
 {name:'Cosmological Constant',q:'Why is observed vacuum energy so small compared with naive quantum-field estimates?',boundary:'The hierarchy is unresolved.',probe:'Test whether a proposed mechanism predicts something beyond restating the observed value.'},
 {name:'Quantum Foundations',q:'Which operational principles uniquely determine quantum theory, and where could they fail?',boundary:'Reconstructions exist but do not settle ontology or all extensions.',probe:'Find a minimal assumption whose removal changes experimentally accessible predictions.'}
];
function log(s){const d=document.createElement('div');d.className='logline';d.textContent='› '+s;ui('log').prepend(d);while(ui('log').children.length>11)ui('log').lastChild.remove()}
function addMob(){mobs.push({x:player.x+(Math.random()-.5)*1600,y:player.y+(Math.random()-.5)*1600,r:8+Math.random()*14,hp:20+Math.random()*50})}for(let i=0;i<70;i++)addMob();for(let i=0;i<30;i++)signals.push({x:(Math.random()-.5)*4000,y:(Math.random()-.5)*4000});
function mutateWorld(){state.epoch++;state.eventT=0;state.chaos=.7+Math.random()*1.8;profile.events++;save();const names=['Gravity blinked','A city spawned upside-down','Every portal changed its destination','The rain began falling sideways','A boss arrived from a future patch','The map split into contradictory histories'];log('WORLD EVENT: '+names[Math.floor(Math.random()*names.length)]);for(let i=0;i<5;i++)addMob()}
function pulse(){profile.pulses++;for(const m of mobs){if(Math.hypot(m.x-player.x,m.y-player.y)<130)m.hp-=24}save()}
function secretStep(k){const map={q:1,2:2,e:3,3:4,r:5,1:6};const v=map[k];if(!v)return;state.secret.push(v);if(state.secret.length>6)state.secret.shift();if(state.secret.join(',')==='1,2,3,4,5,6'&&!state.fuzzball){state.fuzzball=true;profile.discoveries.push('Fuzzball');save();log('??? FUZZBALL MATERIALIZED BETWEEN CARRIERS ???');openFrontier()}}
function openFrontier(){const p=frontierProblems[Math.floor(Math.random()*frontierProblems.length)];state.frontier=p;ui('frontier').textContent=`FUZZBALL // ${p.name} — ${p.q} Boundary: ${p.boundary} Probe: ${p.probe} Status: UNRESOLVED.`;log('Fuzzball opened a Quantum Frontier encounter: '+p.name)}
function interact(){let best=null,bd=75;for(const s of signals){const d=Math.hypot(s.x-player.x,s.y-player.y);if(d<bd){best=s;bd=d}}if(best){signals.splice(signals.indexOf(best),1);player.xp+=10;log('Signal absorbed');if(state.fuzzball&&Math.random()<.35)openFrontier()}}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();keys.add(k);secretStep(k);if(e.code==='Space'){e.preventDefault();pulse()}if(k==='e')interact();if('123'.includes(k)){state.carrier=+k-1;log('Carrier lens '+['geometry','semantic','rhythm'][state.carrier])}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));
function update(dt){state.t+=dt;state.eventT+=dt;if(state.eventT>state.eventEvery)mutateWorld();let ax=0,ay=0;if(keys.has('a')||keys.has('arrowleft'))ax--;if(keys.has('d')||keys.has('arrowright'))ax++;if(keys.has('w')||keys.has('arrowup'))ay--;if(keys.has('s')||keys.has('arrowdown'))ay++;if(ax||ay){const n=Math.hypot(ax,ay);player.vx+=ax/n*.45;player.vy+=ay/n*.45;profile.moves++}player.vx*=.88;player.vy*=.88;player.x+=player.vx*60*dt;player.y+=player.vy*60*dt;for(const m of mobs){const d=Math.hypot(player.x-m.x,player.y-m.y)||1;m.x+=(player.x-m.x)/d*8*dt*state.chaos;m.y+=(player.y-m.y)/d*8*dt*state.chaos;if(d<m.r+10){player.hp-=10*dt;if(player.hp<0){player.hp=100;player.x=player.y=0;profile.failures++;save();log('You reformed. Failure preserved.')}}}mobs.splice(0,mobs.length,...mobs.filter(m=>m.hp>0));if(player.xp>=100*player.level){player.xp-=100*player.level;player.level++;player.hp=100;log('LEVEL '+player.level)}}
function draw(){x.clearRect(0,0,W,H);const g=x.createRadialGradient(W/2,H/2,20,W/2,H/2,Math.max(W,H));g.addColorStop(0,['#112a33','#2d1530','#302713'][state.carrier]);g.addColorStop(1,'#030508');x.fillStyle=g;x.fillRect(0,0,W,H);const sx=v=>v-player.x+W/2,sy=v=>v-player.y+H/2;for(const s of signals){x.fillStyle='#ffe66e';x.beginPath();x.arc(sx(s.x),sy(s.y),4,0,Math.PI*2);x.fill()}for(const m of mobs){x.fillStyle='#7cf8ff';x.beginPath();x.arc(sx(m.x),sy(m.y),m.r,0,Math.PI*2);x.fill()}x.fillStyle=state.fuzzball?'#ff7cf2':'#fff';x.beginPath();x.arc(W/2,H/2,12,0,Math.PI*2);x.fill();if(state.fuzzball){x.strokeStyle='#ff7cf2';x.beginPath();x.arc(W/2,H/2,32+Math.sin(state.t*5)*6,0,Math.PI*2);x.stroke()}}
function hud(){ui('status').textContent=`LV ${player.level} · HP ${Math.round(player.hp)} · XP ${Math.round(player.xp)} · epoch ${state.epoch} · carrier ${state.carrier+1}`;ui('event').textContent=`Next mutation in ${Math.max(0,state.eventEvery-state.eventT).toFixed(1)}s · chaos ${state.chaos.toFixed(2)}`;ui('quest').textContent=state.fuzzball?'Artifact state: FUZZBALL // quantum frontier enabled':'Quest: explore, survive, and discover consequential distinctions.'}
ui('reset').onclick=()=>{localStorage.removeItem('df-mmorpg');location.reload()};let last=performance.now();function frame(t){const dt=Math.min(.05,(t-last)/1000);last=t;update(dt);draw();hud();requestAnimationFrame(frame)}requestAnimationFrame(frame);mutateWorld();log('World initialized. It will not stay still.');
